# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Vision & Voice Localization Camera
description: >- # this means to ignore newlines until "baseurl:"
  This is a project page for UCLA ECE M202A final project.
baseurl: "/vision-voice-localization-camera" # the subpath of the site
url: "https://yukangzhuu.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Required Submissions

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: yukangzhu@g.ucla.edu
      link: mailto:yukangzhu@g.ucla.edu
    - name: Email
      value: duanhy12@ucla.edu
      link: mailto:yukangzhu@g.ucla.edu
  follow:
    - name: LinkedIn
      link: https://www.linkedin.com/in/yukang-zhu-b33a6a250/
    - name: GitHub
      link: http://github.com/yukangZhuu

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
