theme: jekyll-theme-minima
show_downloads: true

# google_analytics:[Your Google Analytics tracking ID]

# Name of website
title: Vision & Voice Localization Camera
description: Project for UCLA ECEM202A/CSM213A (Fall 2021)
